### GET page
GET https://www.searchenginejournal.com/category/seo/

###
POST https://hook.eu2.make.com/8h2s8i6yn8vkeb71f1bilhcp8vakjpnm
Content-Type: application/json

{
  "question": "What is football?"
}

###
POST https://hook.eu2.make.com/b7bdrl49ofu8aaueivswajgiom3jd5ty
Content-Type: application/json

{
  "question": "I like pizza"
}
